### ISSUE TITLE
JSON client request

### ISSUE THREAD

**Issue by tejastank** [MollsReis/junior#17]
Hello,

How to request as json and get response as json from client.

Also Any rpc js support to call server ?

**Comment by MollsReis** [comment]
I'm not sure I understand your question. Have you read the JSON-RPC documentation? Are you looking for a Javascript JSON-RPC client?

**Comment by tejastank** [comment]
Hello, 

Thanks for your response.

But I have resolve it, I am looking for javascript jsonrpc client. which I got that.

Thanks,
Tejas
