### ISSUE TITLE
PHP opening and closing tags

### ISSUE THREAD

**Issue by simionea** [MollsReis/junior#2]
Hi!

I noticed that the files "client.php" and "server.php" in the root directory use short opening tags. However, using these tags is not recommended in code meant for redistribution, because short tags may not be supported on the target server.
I recommend changing them to "long" tags -- "<?php".

And regarding the closing tags -- the PHP manual has the following note:

The closing tag of a PHP block at the end of a file is optional, and in some cases omitting it is helpful when using include() or require(), so unwanted whitespace will not occur at the end of files, and you will still be able to add headers to the response later. It is also handy if you use output buffering, and would not like to see added unwanted whitespace at the end of the parts generated by the included files.

So maybe it's a good idea to remove them at the end of the files (all the files). Or at least the newlines and other whitespace should be removed after the closing tags.

**Comment by MollsReis** [comment]
Thanks for the suggestions! Will use long tags in the root client and server files and clean up that whitespace after the closing tags. These changes will be in the next release, 0.0.4, which should be released this week.
